### ISSUE TITLE
Bug: on Firefox the mouse wheel doesn't work if the mouse cursor is on a youtube embedded video

### ISSUE THREAD

**Issue by bitliner** [malihu/malihu-custom-scrollbar-plugin#104]
I explained the problem here http://stackoverflow.com/questions/19316625/firefox-scrolling-iframe-that-contains-embed-youtube-video .

The demo is here http://plnkr.co/edit/VHgjplC9o57b0rickPZt?p=preview (open it with Firefox).

Try the demo, scroll inside the iframe in the page.

I report the explained problem from stackoverflow:
***************\* from http://stackoverflow.com/questions/19316625/firefox-scrolling-iframe-that-contains-embed-youtube-video

`
Scenario

My page p1 contains an iframe. The iframe points to a page p2 containing an embedded video from youtube.

Problem

The problem is that if I scroll (by mouse) the page inside the iframe, it scrolls normally only if the mouse cursor isn't on a youtube embdedded video.

But if the mouse cursor is on a youtube embedded video, the page p2 inside the iframe stops to scroll, while the external page p1 starts to scroll.

How can avoid this no normal behaviour?

I expect that even if the mouse cursor is on the youtube embedded video, the page inside the iframe continues to scroll normally, and it doesn't loose the mousewheel event.

Failed solutions

I tried to add the attribute wmode="transparent" to the iframe tag of youtube embedded video, but it doesn't solve the problem.

Details

To scroll inside the iframe I'm using a plugin that substitues the scrollbar.

Demo

You can find the demo here. Open it with Firefox and scroll with the mouse inside the iframe

`

**Comment by MatthiasDebaere** [comment]
Can we re-open this? It seems to me this exact bug is now back, on Chrome and on Firefox (and also on mobile device)

**Comment by malihu** [comment]
@MatthiasDebaere 
This is not a bug. It's a browser/javascript security limitation regarding cross-domain iframes. 
Please check the [iframe_example.html](https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/examples/iframe_example.html#L63) to see a workaround/hack.

**Comment by Darex1991** [comment]
@malihu but the demo is not working correctly.
Try this steps:
1. Scroll working on iframe_example
2. Click page (scrolling doesn't work)
3. Move cursor outside of container (space without that scroll container)
4. Move back and cursor now correctly working.

It should be working without moving cursor outside the container.

[scroll.mp4.zip](https://github.com/malihu/malihu-custom-scrollbar-plugin/files/591874/scroll.mp4.zip)

**Comment by malihu** [comment]
@Darex1991 Yes, that's why I said it's a "hack". 
You're right when you say "It should be working without moving cursor outside the container" but the problem is that it can't be done due to browser/javascript limitation on cross-domain iframes.

**Comment by Darex1991** [comment]
Ohh :( Do you have another idea to fix that?

**Comment by malihu** [comment]
Nope. There's no actual fix because you can't bypass browser's policy.

**Comment by Darex1991** [comment]
But why scroll is working when I'm not using scroll plugin? Just default `overflow scroll` on container.

**Comment by malihu** [comment]
Because the browser handles its native scrollbar internally as an application. The custom scrollbar (like all custom scrollbars) is based on javascript (dragging it, using the mouse-wheel etc. are all based on javascript events) and javascript events are not allowed/triggered over iframes that host content that is on a different domain. This is a browser limitation which is there for security. 

In short, the issue is that javascript events are not allowed over cross-domain iframes (it doesn't matter if it's a custom scrollbar or another plugin). 

This happens only on cross-domain iframes. If you had an iframe that hosted a page from the same domain, e.g. another page on your site ([like this example](http://manos.malihu.gr/repository/custom-scrollbar/pre-release/examples/iframes-demo/)) everything would work.

**Comment by Darex1991** [comment]
@malihu thank you for the answer. Now I understand :) I'll try to improve a little your 'hack'

**Comment by malihu** [comment]
Cool :)
