### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by bogdy29** [malihu/malihu-custom-scrollbar-plugin#163]
Hello

Nice plugin. :)

I am using the plugin and I notice memory leaks, I think because of setInterval
and timeout, which are not cleared on destroy.

Thanks!

**Comment by stelioschar** [comment]
Hello,

I think that this issue still exists. After facing leak problems into my website, I found out that a setInterval is being executed from the mCustomScrollbar plugin.

I also make a simple profiling test here: http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/scrollbar_themes_demo.html

Could you please check the attached screenshot?

![capture](https://cloud.githubusercontent.com/assets/1840002/6213250/5efab5b8-b5f6-11e4-80b9-e128c2120214.PNG)

**Comment by bogdy29** [comment]
I  stopped using it because of the memory leaks, but also the advantage was not very big and also I consider that the user experience for toolbars should be defined by the client browser: mac, windows, firefox, chrome, etc.

**Comment by malihu** [comment]
In version 3.1.0 any memory leaks should be gone.

**Comment by Avessalom1** [comment]
The current version still have memory leaks, they are visible in this example
http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/scrollbar_themes_demo.html

**Comment by Avessalom1** [comment]
It turned out the problem resides in upd function which is called recursively. Usage of setInterval instead of setTimeout allows to get rid of the recursion.
