### ISSUE TITLE
[3.0.2] Uncaught TypeError: Cannot read property 'opt' of undefined - Line 1242

### ISSUE THREAD

**Issue by jordangarside** [malihu/malihu-custom-scrollbar-plugin#169]
/\* 
MOUSE WHEEL EVENT
scrolls content via mouse-wheel 
via mouse-wheel plugin (https://github.com/brandonaaron/jquery-mousewheel)
*/
_mousewheel:function(){
    var $this=$(this),d=$this.data(pluginPfx),o=d.opt,

I'm not sure why I'm getting this error.
I get it multiple times (2-9 times) when reloading a page, although I don't get the error every time I reload the page.

Everything works fine including mousewheel functionality. The error is just annoying in my console :p

I am using the latest version on scrollbar and scrollwheel.

**Comment by moniuch** [comment]
The problem is still there in 3.0.9:

```javascript
		/*
		ANIMATES CONTENT 
		This is where the actual scrolling happens
		*/
		_scrollTo=function(el,to,options){
			var d=el.data(pluginPfx),o=d.opt,
```
