### ISSUE TITLE
mCS_no_scrollbar on div i want to make scrollable

### ISSUE THREAD

**Issue by ghost** [malihu/malihu-custom-scrollbar-plugin#175]
Hello, i commented my issue under your projectsite but i think here it is better to communicate.

I installed the newest plugin. I use JS to set the height for a div (it works all fine). And there are no console errors. But it always sets a mCS_no_scrollbar on the div i want to make scrollable.

So there is one big div. in this one there is the #scroller. The scroller should be in the center and have 100% height. This all works. Then there is a table inside. it is about 4k pixel high, but i couldn´t scroll.

**Comment by giorgiberia** [comment]
i have same issue and  mCS_no_scrollbar  is added renewing this file doesn't help 
please save me!
