### ISSUE TITLE
Scrolling back to top

### ISSUE THREAD

**Issue by coldpumpkin** [malihu/malihu-custom-scrollbar-plugin#216]
After I implemented it on body, the back to top link stopped working. How can I scroll back to top of the page with this plugin?

**Comment by coldpumpkin** [comment]
That worked perfectly! Thanks for the late reply.

**Comment by krystyna93** [comment]
I tried doing it this way:
//scroll to top sign up button
    $('.scroll-to-top').on('click', function (e) {
        e.preventDefault();
        //$('html, body').animate({ scrollTop: 0 }, 800);
        $(".body").mCustomScrollbar("scrollTo", "top");
    });

and it worked! :)
