### ISSUE TITLE
Add mCustomScrollbar() dynamically / content replacement

### ISSUE THREAD

**Issue by simogeo** [malihu/malihu-custom-scrollbar-plugin#228]
Hi, first, thanks for this elegant plugin.

I' like to know one thing. I init a page with a `filefinfo` div and this is how I use your plugin : 

``` javascript
$("#fileinfo").mCustomScrollbar({
                theme:csTheme,
                scrollButtons:{enable:csButton},
                advanced:{ autoExpandHorizontalScroll:false, updateOnContentResize: true },
                axis: "y"
            });
```

But replacing the content of my div using `$('#fileinfo').html(template);` just destroy my customed scrollbar. 
I'm surprised by this behavior Is that normal ??? And how can I keep it or recreate it dynamically

I use the latest from repository

Thanks!

**Comment by alxkos** [comment]
in my case i'm just destroying the object before setting new one
```
self.$contentWindow.mCustomScrollbar("destroy");
self.$contentWindow.mCustomScrollbar();
```

working like charm
