### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by M0on75e1l** [malihu/malihu-custom-scrollbar-plugin#234]
First of all, I want to thank you for creating such a great tool, and sorry for my bad English, hope you will be able to understand what I am trying to ask.
I am new to things like RequireJS and CommonJS, so for learning purposes I am now working on a small jQuery-based chat application, based on CommonJS approach for including dependencies and Gulp with Browserify for browser support. I also want your plugin for scrollbars. I've installed npm-package, and now, when I am trying to include it in my "chat.js" file with "require(...), it behaves just like if I include it using "script" tags, assigning itself to a global jQuery object. One of my aims was to create a chat module, which I can just take, and place into another project, without worrying about dependencies. So the chat will have it's own local npm-required jQuery object, and all other necessary libraries included locally. My question is: how can I assign this plugin to some local jQuery object in my module, to use it with browserify? Or is this a wrong approach of using CommonJS? I've seen some other tools like browserify-shim, but I am not sure is this what I really need. I understand that maybe this question is a little offtopic, but anyway hope you can give me some ideas.

**Comment by jesusprubio** [comment]
Hi, you're right, really we need the same because to pollute the global namespace is a bad practice. Moreover is a must in situations like described here: https://github.com/twbs/bootstrap/pull/15640#issuecomment-71096192

I'm trying to make this library compatible with browserify (in this way) but I thin I need help from developers of the project. :(

**Comment by ibc** [comment]
:+1: bad globals

**Comment by M0on75e1l** [comment]
@jesusprubio browserify-shim could help, but it looks like dirty solution for me, leading to some another inconveniences. We need real browserify support, but unfortunately it looks like the author is not going to implement it. Are there any alternatives to this plugin, compatible with browserify?

**Comment by jesusprubio** [comment]
Yep I think it's dirty, we don't like it. As a last alternative we're going to fork the repo and make it compatible.

**Comment by malihu** [comment]
I currently don't have time to deal with this. I'm hoping to do it the next update.

**Comment by M0on75e1l** [comment]
@malihu waiting patiently.

**Comment by ibc** [comment]
Please @malihu don't close the issue, let it open a reminder (unless the author prefers it to be closed) :)

**Comment by M0on75e1l** [comment]
@ibc I've closed it accidentally :)

**Comment by malihu** [comment]
Updated plugin (version 3.0.8) and npm. Thanks to @xqwzts

**Comment by M0on75e1l** [comment]
Awesome, thanks to all.
