### ISSUE TITLE
Display bug when applying custom-scrollbar-plugin

### ISSUE THREAD

**Issue by simogeo** [malihu/malihu-custom-scrollbar-plugin#237]
Hi,

First many thanks for this great project ! I integrate it to my [Filemanager application](https://github.com/simogeo/Filemanager) as an option. And by default it is available.

I observed, that sometimes, the scrollbar is not applied correctly on my filetree list. A user [reported the issue](https://github.com/simogeo/Filemanager/issues/302) and has made a video available at : http://tinypic.com/r/2088h90/8

For information , the filetree is created dynamically by calling [createFileTree() method](https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.js#L525).

Do you already experienced that kind of problem ? Any idea to solve it ? Thanks in advance

**Comment by simogeo** [comment]
Me again, 
The timeout option does not work ! Could you explain me what did you mean by `onInit` plugin ?
Thanks

**Comment by malihu** [comment]
The plugin provides a [number of callbacks](http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-callbacks-onInit) as options, which you can use to call your own functions. One of these is the `onInit` callback which is fired when scrollbar has initialized and is ready to use. 
Example: 
```
$(selector).mCustomScrollbar({
    callbacks:{
        onInit:function(){
          console.log("scrollbars initialized");
          /* your functions here */
        }
    }
});
```

More info: 
[User-defined callbacks](http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-callbacks-onInit)
[Callback options](http://manos.malihu.gr/jquery-custom-content-scroller/#callbacks-section)

**Comment by simogeo** [comment]
Sorry I missed this. Many thanks !!!

**Comment by anastasiiayushko** [comment]
по чему скролл не скрывается, если контент в блоке не достиг определенной высоты класс no_scrollbar не добавляется?
