### ISSUE TITLE
scrollButtons scrollType stepped not working

### ISSUE THREAD

**Issue by RMK147** [malihu/malihu-custom-scrollbar-plugin#240]
When using the following settings, if I set the scrollType property to 'stepped' for scrollButtons, the buttons no longer work, however they will work if I set it to 'stepless' or remove the property completely.

```
        $('#table-list').mCustomScrollbar({
            axis: 'y',
            theme: 'dark-3',
            snapAmount: 197,
            scrollInertia: 0,
            scrollButtons: {
                enable: true,
                scrollAmount: 197,
                scrollType: 'stepped'
            },
            mouseWheel: {
                enable: true,
                scrollAmount: 197
            }
        });
```

**Comment by krzysztofadamczewski** [comment]
It's still doesn't work for touch devices:(
Code:

var height= 86;
$(".container").mCustomScrollbar({
        setHeight: false,
        autoExpandScrollbar:true,
        snapAmount: height,
        mouseWheel: {
            enable: false,
            scrollAmount: height,
            normalizeDelta:true
        },
        keyboard: {
            enable: false,
            scrollAmount: height
        },
        scrollButtons: {
            enable: true,
            scrollAmount: 1,
            scrollType: "stepped"
        },
        advanced: {
            updateOnContentResize: true
        },
        scrollInertia: 1,
        contentTouchScroll: 10000,
        documentTouchScroll: false
    });
