### ISSUE TITLE
Keyboard arrows

### ISSUE THREAD

**Issue by BaronSosaa** [malihu/malihu-custom-scrollbar-plugin#247]
Hi,
I've implemented these scrollbars a few times now and they are quite amazing.
However they other day I noticed on none of the keyboard keys work on any of those projects.
For some reason the default doesn't seem to apply, nor do they work when I add the option to the config (keyboard:{ enable:true }). 
When I press the keyboard down arrow for example I can see the mouse cursor dissappearing as it should, but its just not scrolling.
I use CSS to set the height and overflow on the div elements, other then that everything seems to work fine.
Am I missing something here?

**Comment by malihu** [comment]
Normally, the cursor should not disappear. Does it work when you test the plugin demo below? 
http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html

Also, can you send me a link to test it?

**Comment by BaronSosaa** [comment]
Haha ok, now you mention it, I checked my bower.json.
Seems I'm still using the ye old https://github.com/mwagena/malihu-custom-scrollbar-plugin-bower.
Guess I'll have to swap that out. My sincerest apologies for wasting you time on such a stupid thing.
Many thnx!

**Comment by malihu** [comment]
No problem :)
