### ISSUE TITLE
Wordpress and infinite scroll through pages

### ISSUE THREAD

**Issue by coldpumpkin** [malihu/malihu-custom-scrollbar-plugin#250]
Is it possible to, when we reach the end of the page, it loads the other pages (/page/2,3,4,...) with the infinite scroll? How can I achieve this? Thanks.

EDIT: I don't want to retrieve everything from the page though, just all the divs with some class on them, for example. Basically I'm loading all div with class "post" and each post is inside that div, so, I'll go to page2, page3 and so on and grab all the "post" divs and put them in the first page.

**Comment by malihu** [comment]
You should check https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/examples/infinite_scroll_example.html which loads content when scrolling reaches the bottom, as well as https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/examples/ajax_example.html which loads content via ajax. 

You probably want to place your ajax call in plugin's `onTotalScroll` callback, for example: 
```
var url="/path/to/page";
$(".content").mCustomScrollbar({
	callbacks:{
		onTotalScroll:function(){
			$.get(url,function(data){
				$(".content .mCSB_container").append(data);
			});
		},
		onTotalScrollOffset:100, /* optional */
		alwaysTriggerOffsets:false /* optional */
	}
});
```

**Comment by coldpumpkin** [comment]
Thank you, I think that gives me the right direction! Any way to specify which div or divs it's going to get content from?

**Comment by malihu** [comment]
You should check this thread: 
http://stackoverflow.com/questions/5611746/jquery-ajax-load-certain-div

**Comment by coldpumpkin** [comment]
Thank you but I tried and I can't seem to work it it :\ Could you tell me how I can include it in your code?

**Comment by malihu** [comment]
Ajax example loading all .post elements: 
```
var url="/path/to/page";
$(".content").mCustomScrollbar({
    callbacks:{
        onTotalScroll:function(){
            $.ajax({
                url:url,
                cache:false,
                beforeSend:function(xhr){
                    xhr.overrideMimeType("text/plain; charset=utf-8");
                }
            }).done(function(data){
                $(".content .mCSB_container").append($(data).find(".post"));
            });
        },
        onTotalScrollOffset:100, /* optional */
        alwaysTriggerOffsets:false /* optional */
    }
});
```

**Comment by coldpumpkin** [comment]
It's not working :\ tested properly

**Comment by malihu** [comment]
I can't really help as I'd need more info, your full code etc. Do you test it locally? Do you get any console errors?

**Comment by coldpumpkin** [comment]
I've used your demo files. Here is the link http://josemelo.net/test

**Comment by malihu** [comment]
Ok. It doesn't work because of .find() function and the way your remote content markup is set. 
To fix it, change: `$(data).find(".post")`
to: `$(data).filter(".post")`

**Comment by coldpumpkin** [comment]
No, still nothing. I updated the files, you can check.

**Comment by malihu** [comment]
It's working. Scroll to the very bottom and see the `olé` text :)

**Comment by coldpumpkin** [comment]
That works great indeed :) I was just wondering if we can reset the family tree in the url? Because if I put like `var url="http://google.pt"` it will assume `http://josemelo/test/http://google.pt`.

I think I need this because it's not working in my wordpress page. Probably because I have include of pages like `<?php get_template_part('content'); ?>` which outputs something like http://...

**Comment by coldpumpkin** [comment]
It works great! Thank you sir!
