### ISSUE TITLE
initializing not with window load doesnt work

### ISSUE THREAD

**Issue by mamezito** [malihu/malihu-custom-scrollbar-plugin#252]
i have dimanic DOM elements, and want to initialize mcustomscrollbar after element appear in DOM
but running the function  get this

TypeError: undefined is not a function (evaluating '$(".customScrolled").mCustomScrollbar()')

**Comment by malihu** [comment]
You can use the `live` option parameter and call `mCustomScrollbar` normally without the need to wait for the dynamic elements: 
`$(".customScrolled").mCustomScrollbar({ live:"on" })` 

More info about live option: 
http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-live

**Comment by mamezito** [comment]
thank you, saved the planet)
will try today
