### ISSUE TITLE
Dropdowns hidden on focus in firefox

### ISSUE THREAD

**Issue by wehrhaus** [malihu/malihu-custom-scrollbar-plugin#254]
In firefox(latest release), when a select is triggered, the options are hidden on mouseover.

**Comment by malihu** [comment]
Can't re-produce this issue (tested it on Firefox 35.0.1). If you can send me your link/code I'd be able to help.

**Comment by wehrhaus** [comment]
I found that this only happens when the select was wrapped in a label tag.
