### ISSUE TITLE
Reaching the end of a div with scroll

### ISSUE THREAD

**Issue by coldpumpkin** [malihu/malihu-custom-scrollbar-plugin#255]
Is it possible to detect whenever we reach the end of a certain div with the scroll? I'm using the infinite scroll function but instead of triggering in the end of the page I want it to be triggered when we reach the end of a div.

**Comment by malihu** [comment]
You could set the `onTotalScrollOffset` to be your div's height. For example: 
`onTotalScrollOffset: $("#element-id").height()`

There are more than one ways to do this. Does the above help?

**Comment by coldpumpkin** [comment]
Isn't that outputting the height value instead of triggering when it reaches the height? For example, if my div has 100px height, the offset will be 100px from the bottom of the page up.

**Comment by malihu** [comment]
Oh sorry that was a mistake (I thought you just wanted the last element's height to be your offset). 

You could set `onTotalScrollOffset` dynamically via the `onInit` callback. For example: 
```
$(selector).mCustomScrollbar({
  callbacks:{
    onInit:function(){
      $(this).data("mCS").opt.callbacks.onTotalScrollOffset=Math.abs(this.mcs.content.innerHeight()-($("#element-id").position().top+$("#element-id").outerHeight(true)));
    },
    onTotalScroll:function(){ /* your callback */ },
    alwaysTriggerOffsets:false
  }
});
```

Let me know if this works for what you need

**Comment by coldpumpkin** [comment]
That works perfectly fine :) If it's not abusing too much, is it possible to give it a margin? Like e.g. if I'm close 50px to the end, it'll trigger the scroll :)

Thank you for your time!

**Comment by malihu** [comment]
You could do it by replacing in the code above: 
`$("#element-id").outerHeight(true)`
with:
`($("#element-id").outerHeight(true)-50)`

**Comment by coldpumpkin** [comment]
Thank you brother! :)

**Comment by malihu** [comment]
You're welcome :)

**Comment by vignesh-tharani** [comment]
The above example works like a charm! Thanks for that!
