### ISSUE TITLE
getting undefined is not a function with manual calls in gwt application

### ISSUE THREAD

**Issue by mamezito** [malihu/malihu-custom-scrollbar-plugin#258]
Hi have some strange problem with the script, i load the library, jquery, getting scrollbar initialized, can see it in DOM and also rendered in browser, but when i am trying to work with it, like scroll to bottom or disable and doing manual calls

getting these
$(".customscroled").mCustomScrollbar("disable",true);
VM2670:2 Uncaught TypeError: undefined is not a function

though in pure html manual calls works fine, maybe u have some knowledge on that? thanx

**Comment by malihu** [comment]
Is the selector `.customscroled` correct?
I'm not familiar with the toolkit but maybe the functions are called before loading the custom scrollbar and/or jquery scripts(?)

**Comment by mamezito** [comment]
yeah selector is right, function called after jquery and scrollbar scripts, cause the scrollbar is initialized, i guess something to GWT related, have found a ways to avoid manual calls, thanx anyway
