### ISSUE TITLE
mCS_no_scrollbar always added to DOM

### ISSUE THREAD

**Issue by bittelc** [malihu/malihu-custom-scrollbar-plugin#260]
Javascript:
```javascript
$(window).load( function() {
        SetImageSizes();
        $(".student-header").css("height", "49px");
        $(".student-header").css("overflow-y", "hidden");

        $.getScript("/Scripts/Libraries/jquery.mCustomScrollbar.js", function () {
             $('.student-header').mCustomScrollbar({
                    theme: "dark-2"
                  });
           });
    });
    
```

DOM output:

```HTML
<div class="header student-header mCustomScrollbar _mCS_1 mCS_no_scrollbar" style="height: 49px; overflow-y: hidden;">
<div id="mCSB_1" class="mCustomScrollBox mCS-dark-2 mCSB_vertical mCSB_inside" tabindex="0">
<div id="mCSB_1_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" style="position: relative; top: 0px; left: 0px;" dir="ltr">
<div id="mCSB_1_scrollbar_vertical" class="mCSB_scrollTools mCSB_1_scrollbar mCS-dark-2 mCSB_scrollTools_vertical" style="display: none;width: 8px;height: 50px;">
<div class="mCSB_draggerContainer">
<div id="mCSB_1_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 0px; height: 0px; top: 0px;" oncontextmenu="return false;">
<div class="mCSB_dragger_bar" style="line-height: 0px;"
></div>
</div>
<div class="mCSB_draggerRail" style="width: 8px; height: 9px;">
</div>
</div>
</div>
</div>
</div>
```

I, of course, would like the scrollbar to be appearing and cannot figure out why mCSB_no_scrollbar is being added to the DOM.

**Comment by bittelc** [comment]
@malihu

**Comment by malihu** [comment]
The `$.getScript` should work. Does `.student-header` contain any content? 
The DOM output markup does not seem correct and it has no content.

**Comment by bittelc** [comment]
Definitely! I'm not allowed to post the actual content for copyright purposes!

**Comment by bittelc** [comment]
Contained DOM (content wording changed, but structure kept)

```HTML
<div id="mCSB_1_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" style="position: relative; top: 0px; left: 0px;" dir="ltr">
        <div class="logo">
            <a href="#">there are words here</a>
        </div>
        <div class="another class"></div>
        <div class="student-name-wrapper">
       <div class="student-name"><h3><span id="greeting-message">Hi, </span>You!</h3></div></div>
    </div>
```

**Comment by malihu** [comment]
Do you get any console errors? 

In order for me to help I'd need to see your markup (or your page online). The javascript code you posted is correct so the problem must be somewhere else. 
You can contact me here: http://manos.malihu.gr/contact

**Comment by malihu** [comment]
Can you set the element's height via CSS? 

```
.student-header{
    height: 49px;
}
```

**Comment by malihu** [comment]
I made a fiddle with your code and it does work: http://jsfiddle.net/oy5uwk8y/

**Comment by bittelc** [comment]
Oh man, Malihu, this is great. Let me dig around for another few minutes and I'll get back to you. So odd that it's working on the fiddle but not on my local.

**Comment by bittelc** [comment]
Ah man! You showed me where I was going wrong! Broad scope of problem -- I didn't correctly reference my mCustomScrollbar css file. While I thought this might be possible, I intuitively didn't believe this would effect any of the DOM or cause any problems in the DOM as illustrated in initial issue.
However, immediately after loading the correct css file, everything worked as expected. Could you clarify my new assumption - that not having the correct css file may cause "mCS_no_scrollbar" class to be applied.

**Comment by malihu** [comment]
Plugin CSS is essential for the script to work as it contains the basic styling of all elements, especially the main content wrapper (`.mCustomScrollBox`). Without this, the script cannot calculate correctly content/scrollbar dimensions, so it wrongly assumes that content does not need scrolling (`.mCSB_no_scrollbar`). 

The script itself adds very few inline styles. It mostly toggles classes and all the classes rules are defined in jquery.mCustomScrollbar.css. This was done on purpose as it gives the developer the freedom to change many core things via CSS without modifying the javascript (it's basically the reason you can design any kind of scrollbar).

**Comment by bittelc** [comment]
Awesome. Thank you for all the help! It makes complete sense now.

**Comment by rafaqf** [comment]
Would be nice if any console log is shown when this happens! I've been struggling my head until I found this, never thought that the CSS plugin is so essential. 

A console log warning that the css plugin is not loaded would be great to warn that something is missing.

Thanks a lot!

**Comment by malihu** [comment]
@rafaqf Thanks for the feedback! I'll try and see if/how to add such warning on the next version.
