### ISSUE TITLE
Prevent page scrolling

### ISSUE THREAD

**Issue by apolzon** [malihu/malihu-custom-scrollbar-plugin#263]
Is there a way to prevent page scrolling when the end of content is reached? I expected the `onTotalScroll` callback to pass an event, which I would hopefully be able to use to prevent the default browser scroll behavior.

I'm trying to migrate an application from nanoscroller.js, and this is a feature nanoscroller provides which I've found very useful.

Thanks, great work on the plugin.

**Comment by malihu** [comment]
Yes of course. Set [mousewheel: preventDefault](http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-mouseWheel-preventDefault) option parameter to `true`: 
`mouseWheel:{ preventDefault: true }`

**Comment by apolzon** [comment]
Great, thanks.

However, I just realized my issue is that I have a mcustomscrollbar element inside another mcustomscrollbar element, so using prevent default doesn't accomplish what I'm looking for.

I guess what I really want is to prevent the scroll in the child element from bubbling up to the parent.

**Comment by malihu** [comment]
Using `preventDefault` option on a child mcustomscrollbar element, will stop the parent element (body or another mcustomscrollbar) from scrolling. Isn't this what you need?

**Comment by apolzon** [comment]
heh, it does indeed -- I had a typo of mousewheel instead of mouseWheel. Sorry for the trouble.

**Comment by malihu** [comment]
No problem :)

**Comment by ghost** [comment]
Not working on android browsers.
