### ISSUE TITLE
Scroll both axis at the same time

### ISSUE THREAD

**Issue by xavicolomer** [malihu/malihu-custom-scrollbar-plugin#270]
Is there any way to scroll both axis at the same time?

Great work!

**Comment by malihu** [comment]
Yes, you can use an array: [y,x]. For example: 
`$(selector).mCustomScrollbar("scrollTo",[100,50]);`

**Comment by xavicolomer** [comment]
Hi Malihu,

I meant using the mouswheel, to scroll both axis at the same time, as if the component is overflowed by height and width and the container overflow is set to scroll.

Right now I can just scroll vertically.

Thanks!

**Comment by xavicolomer** [comment]
I had to slightly change your code in order to allow multiple axis scrolling interaction. The code can be improved simplifying the logic.

if (o.axis.indexOf("x")) {} ...

But I am not sure I will break anything :) Maybe I will give it a try later on. Thanks again!

if (o.axis === "x" || o.axis === "y") {
                    if(o.axis==="x" || o.mouseWheel.axis==="x"){
                        var dir="x",
                            px=[Math.round(deltaFactor*d.scrollRatio.x),parseInt(o.mouseWheel.scrollAmount)],
                            amount=o.mouseWheel.scrollAmount!=="auto" ? px[1] : px[0]>=mCustomScrollBox.width() ? mCustomScrollBox.width()*0.9 : px[0],
                            contentPos=Math.abs($("#mCSB_"+d.idx+"_container")[0].offsetLeft),
                            draggerPos=mCSB_dragger[1][0].offsetLeft,
                            limit=mCSB_dragger[1].parent().width()-mCSB_dragger[1].width(),
                            dlt=e.deltaX || e.deltaY || delta;
                    }else{
                        var dir="y",
                            px=[Math.round(deltaFactor*d.scrollRatio.y),parseInt(o.mouseWheel.scrollAmount)],
                            amount=o.mouseWheel.scrollAmount!=="auto" ? px[1] : px[0]>=mCustomScrollBox.height() ? mCustomScrollBox.height()*0.9 : px[0],
                            contentPos=Math.abs($("#mCSB_"+d.idx+"_container")[0].offsetTop),
                            draggerPos=mCSB_dragger[0][0].offsetTop,
                            limit=mCSB_dragger[0].parent().height()-mCSB_dragger[0].height(),
                            dlt=e.deltaY || delta;
                    }
                    if((dir==="y" && !d.overflowed[0]) || (dir==="x" && !d.overflowed[1])){return;}
                    if(o.mouseWheel.invert){dlt=-dlt;}
                    if(o.mouseWheel.normalizeDelta){dlt=dlt<0 ? -1 : 1;}
                    if((dlt>0 && draggerPos!==0) || (dlt<0 && draggerPos!==limit) || o.mouseWheel.preventDefault){
                        e.stopImmediatePropagation();
                        e.preventDefault();
                    }
                    _scrollTo($this,(contentPos-(dlt*amount)).toString(),{dir:dir});
                } else if (o.axis === "yx") {
                    var dirX="x",
                        px=[Math.round(deltaFactor*d.scrollRatio.x),parseInt(o.mouseWheel.scrollAmount)],
                        amountX=o.mouseWheel.scrollAmount!=="auto" ? px[1] : px[0]>=mCustomScrollBox.width() ? mCustomScrollBox.width()*0.9 : px[0],
                        contentPosX=Math.abs($("#mCSB_"+d.idx+"_container")[0].offsetLeft),
                        draggerPosX=mCSB_dragger[1][0].offsetLeft,
                        limitX=mCSB_dragger[1].parent().width()-mCSB_dragger[1].width(),
                        dltX=e.deltaX || e.deltaY || delta;

                    var dirY="y",
                        px=[Math.round(deltaFactor*d.scrollRatio.y),parseInt(o.mouseWheel.scrollAmount)],
                        amountY=o.mouseWheel.scrollAmount!=="auto" ? px[1] : px[0]>=mCustomScrollBox.height() ? mCustomScrollBox.height()*0.9 : px[0],
                        contentPosY=Math.abs($("#mCSB_"+d.idx+"_container")[0].offsetTop),
                        draggerPosY=mCSB_dragger[0][0].offsetTop,
                        limitY=mCSB_dragger[0].parent().height()-mCSB_dragger[0].height(),
                        dltY=e.deltaY || delta;

                    if((dirY==="y" && !d.overflowed[0]) || (dirX==="x" && !d.overflowed[1])){return;}
                    if(o.mouseWheel.invert){dltX=-dltX;dltY=-dltY;}
                    if(o.mouseWheel.normalizeDelta){dltX=dltX<0 ? -1 : 1;dltY=dltY<0 ? -1 : 1;}
                    if((dltX>0 && draggerPosX!==0) || (dltX<0 && draggerPosX!==limitX) || (dltY>0 && draggerPosY!==0) || (dltY<0 && draggerPosY!==limitY) || o.mouseWheel.preventDefault){
                        e.stopImmediatePropagation();
                        e.preventDefault();
                    }
                    _scrollTo($this,(contentPosX-(dltX*amountX)).toString(),{dir:dirX});
                    _scrollTo($this,(contentPosY-(dltY*amountY)).toString(),{dir:dirY});
                }
