### ISSUE TITLE
OnTotalScroll issue

### ISSUE THREAD

**Issue by sahar176** [malihu/malihu-custom-scrollbar-plugin#28]
While trying to auto load content with OnTotalScroll, I noticed that if I scroll down continuously it won't fire the event until scrolling is stopped.

The issue can be reproduced here: http://manos.malihu.gr/tuts/custom-scrollbar-plugin/issue_2_fix_test/infinite_scroll_examples-issue_2.html.

**Comment by ekr3peeK** [comment]
The bug is still present in 3.15.0.
