### ISSUE TITLE
Flickering  issue depending on content

### ISSUE THREAD

**Issue by simogeo** [malihu/malihu-custom-scrollbar-plugin#281]
A Filemanager user opened an issue regarding scrollbar flixkering after resize. Here you'll find the thread : https://github.com/simogeo/Filemanager/issues/334

It seems to be a custom-scrollbar-plugin issue. Do you have any clue regarding this ? 
Thanks

**Comment by malihu** [comment]
I think you already solve it by enabling `alwaysShowScrollbar` option. This or you could change the CSS right margin value(s) in jquery.mCustomScrollbar.css

**Comment by simogeo** [comment]
ok. Thanks.
