### ISSUE TITLE
Possible to assign properties via data attributes?

### ISSUE THREAD

**Issue by webdes03** [malihu/malihu-custom-scrollbar-plugin#292]
Great implementation of a custom scrollbar plugin. This is way more flexible than a lot of the others I've seen!

Quick question though... I love the ability to define the theme and axis via data attributes on the element. Is it possible to set things like the inertia in the same manner, ie data-msc-inertia, or are those properties only available via the JavaScript object?

**Comment by malihu** [comment]
These are only available via js (can't really say if/when more options will be available via html).
Thanks for your comments and feedback.

**Comment by webdes03** [comment]
Thanks for the quick reply... if I add any of that I'll share :-)
