### ISSUE TITLE
Scrollbar within JQuery-ui dialog

### ISSUE THREAD

**Issue by kae24** [malihu/malihu-custom-scrollbar-plugin#295]
I'm trying to set scrollbars for a jquery-ui dialog window. scrollbars work for x and y individually but when i set the config "axis: yx" all items in the dialog window disappears.

Any ideas?

**Comment by malihu** [comment]
Sounds like the element with the scrollbars needs a width/height set. I can't really tell though unless I see your page...

**Comment by kae24** [comment]
It works if width and height are not set to auto, is there anyway to have it work with auto?

**Comment by malihu** [comment]
Probably not (according to element markup). I don't know what you're trying to do, but why do you need auto/auto? Can you set it to 100%?

**Comment by kae24** [comment]
There are elements within the jquery dialog window, that are set to a percentage. scrollbars work fine if axis is set to x, or y, not 'yx'.


Heres a quick mockup,
http://kevinly.ca/vb/
