### ISSUE TITLE
Vertically/Horizontally Problem in Google Chrome

### ISSUE THREAD

**Issue by Blackeye** [malihu/malihu-custom-scrollbar-plugin#303]
Hej malihu!

I just wanted to add the following issue also here in the repo (http://manos.malihu.gr/jquery-custom-content-scroller/comment-page-64/#comment-19528). Maybe some of the other users has a hint for me how to temporarily fix this problem:

I’ve updated to 3.0.8 of your plugin to get the fix to be scrollable horizontally, if the slider is vertically (see your comment here: http://stackoverflow.com/a/26496368/4323473). This works on good on the samsung internet browser, the sailfish and other browsers. But I didn’t get it working on the chrome on Android. Can you confirm this problem and do you have an idea how to fix it?

Yours,
Blackeye

**Comment by malihu** [comment]
Yes I can confirm this but I can't say when I'll have a fix for this. I hope to find some time in the coming weeks to check it thoroughly and implement a solution.

**Comment by Blackeye** [comment]
Just a short question malihu!

Do you if this is a problem of a newer version of the plugin, or because chrome made problem making changes?

**Comment by Blackeye** [comment]
You're great malihu! Thx for fixing this issue!
