### ISSUE TITLE
Drag the scroller out of browser window

### ISSUE THREAD

**Issue by helenaaraujo** [malihu/malihu-custom-scrollbar-plugin#307]
Hello, Malihu,

The problem happens when I drag the scroller and move the mouse out of the browser window and release it. When I move the mouse back to the browser, the scroller still moves according to the mouse movement until I click the mouse again.
Is there a way to prevent the scroll event from propagating, when I move the mouse back to the browser?

I've tried this, but didn't work.

 $(scroll).mouseenter(function (event) {

       $buttonsDiv.mCustomScrollbar("stop");

 }).mouseleave(function () {
    
        $buttonsDiv.mCustomScrollbar("update");

 });

Thank you.

**Comment by malihu** [comment]
Hi, 

I can't seem to reproduce this. Can you provide more info (browser, OS, option parameters used etc.) or a test page/code?

**Comment by helenaaraujo** [comment]
It happens on IE (I tried on IE 11). On Chrome works fine.
I used one of your horizontal scrollbar examples.

Thank you.

**Comment by malihu** [comment]
Doesn't seem to happen when I test the [main demo](http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html) on IE11 (in Windows 7).

**Comment by helenaaraujo** [comment]
I tested with Windows 8... it only happens once in a while.
Thanks anyway :)

**Comment by malihu** [comment]
I still can't reproduce this issue (tested it on latest IE/Win 8.1). Maybe some application in your windows  installation gained focus the moment you release the dragger(?) 
In any case, this seems like an issue out of the plugin scope or something that can't be solved within the script.
