### ISSUE TITLE
Element with "position: absolute" is removed from container after calling mCustomScrollbar()

### ISSUE THREAD

**Issue by luxigo** [malihu/malihu-custom-scrollbar-plugin#311]
Hello !

I have something like this:

     <div id="container">
        <a id="handle" style="position: absolute; top: -1em;">
            <div class="fa fa-angle-double-down"></div>
        </a>
     </div>

During the call to "$('#container').mCustomScrollbar();" the #handle element is removed.

When the position attribute is 'fixed', the #handle element is not removed. 

I looked briefly in your code but could not fix it, so I had to add the element afterwards.

Thanks !

**Comment by luxigo** [comment]
Still here - just not visible, just had $('#handle').prependTo('#container') after mCustomScrollbar() initialization.

**Comment by malihu** [comment]
Is it visible if you change its top position to a positive value (e.g. `top: 1em`)? 

It might get hidden simply because custom scrollbar's content wrapper (`.mCSB_container`) overflow is `hidden`. You could change it to `overflow: visible` if this is the case.
