### ISSUE TITLE
ui autocomplete click the up/down arrows to navigate to lists in autocomplete lists

### ISSUE THREAD

**Issue by ligori-jebaraja** [malihu/malihu-custom-scrollbar-plugin#323]
now its using mouse selection only. 
Need a solution for this asap

**Comment by malihu** [comment]
Like [this example](http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/jquery_ui_autocomplete_example.html)?

**Comment by malihu** [comment]
If yes, just add the [focus event](http://api.jqueryui.com/autocomplete/#event-focus) in the autocomplete function in [jquery_ui_autocomplete_example.html](https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/examples/jquery_ui_autocomplete_example.html): 

```
focus:function(e,ui){
	var el=$(".ui-state-focus").parent();
	if(!el.is(":mcsInView") && !el.is(":hover")){
		$(".ui-autocomplete").mCustomScrollbar("scrollTo",el,{scrollInertia:0,timeout:0});
	}
},
```

View the source of http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/jquery_ui_autocomplete_example.html for the complete code.

**Comment by ligori-jebaraja** [comment]
Thanks for your quick update. It seems to be working now. However when I start typing 'a' it should select corresponding list in the autocomplete list. So that I can easily navigate other selections using up/down arrows

**Comment by malihu** [comment]
Change the focus event to: 

```
focus:function(e,ui){
	if(!ui.item){
		var first=$(".ui-autocomplete li:first");
		first.trigger("mouseenter");
		$(this).val(first.data("uiAutocompleteItem").label);
	}
	var el=$(".ui-state-focus").parent();
	if(!el.is(":mcsInView") && !el.is(":hover")){
		$(".ui-autocomplete").mCustomScrollbar("scrollTo",el,{scrollInertia:0,timeout:0});
	}
},
```

**Comment by ligori-jebaraja** [comment]
Perfect !!! Thanks lot...
