### ISSUE TITLE
mCustomScrollbar is not a function

### ISSUE THREAD

**Issue by yi2020** [malihu/malihu-custom-scrollbar-plugin#336]
I'm trying to use mCustomScrollbar but am getting the above error. I looked at https://github.com/malihu/malihu-custom-scrollbar-plugin/issues/194 thinking it might be related, as well as some other discussions online.

However, I can't figure out why it's happening. It is probably something to do with code conflicts. I use squarespace and it has its own set of JSes it uses, in addition to other scripts I've brought on. Problem is, I can't figure out where the conflict is and there are no errors to the console that describe it.

This is the page where the error occurs:
http://bit.ly/1gb11kZ

**Comment by malihu** [comment]
Can you try calling `mCustomScrollbar` function on `$(window).load()` instead of `$(document).ready()`?

**Comment by yi2020** [comment]
Tried, didn't solve it. What else?

**Comment by malihu** [comment]
Try changing `$(window).load(function() {` to `jQuery(window).load(function() {`

**Comment by yi2020** [comment]
Still didn't work. Is there a way to turn on debug for mCustomScrollbar so that we see it loaded correctly, modified the prototypes, registered the listeners, etc.?

**Comment by yi2020** [comment]
I loaded the un-minified version on the website now. It looks like the init isn't going as expected. This code is never entered (I put a breakpoint on the var statement). Why would that selector fail?

				return $(selector).each(function(){
					
					var $this=$(this);
					
					if(!$this.data(pluginPfx)){ /* prevent multiple instantiations */
					
						/* store options and create objects in jquery data */
						$this.data(pluginPfx,{
							idx:++totalInstances, /* instance index */
							opt:options, /* options */
							scrollRatio:{y:null,x:null}, /* scrollbar to content ratio */
							overflowed:null, /* overflowed axis */
							contentReset:{y:null,x:null}, /* object to check when content resets */
							bindEvents:false, /* object to check if events are bound */
							tweenRunning:false, /* object to check if tween is running */
							sequential:{}, /* sequential scrolling object */
							langDir:$this.css("direction"), /* detect/store direction (ltr or rtl) */
							cbOffsets:null, /* object to check whether callback offsets always trigger */
							/* 
							object to check how scrolling events where last triggered 
							"internal" (default - triggered by this script), "external" (triggered by other scripts, e.g. via scrollTo method) 
							usage: object.data("mCS").trigger
							*/
							trigger:null
						});
						
						var d=$this.data(pluginPfx),o=d.opt,
							/* HTML data attributes */
							htmlDataAxis=$this.data("mcs-axis"),htmlDataSbPos=$this.data("mcs-scrollbar-position"),htmlDataTheme=$this.data("mcs-theme");
						 
						if(htmlDataAxis){o.axis=htmlDataAxis;} /* usage example: data-mcs-axis="y" */
						if(htmlDataSbPos){o.scrollbarPosition=htmlDataSbPos;} /* usage example: data-mcs-scrollbar-position="outside" */
						if(htmlDataTheme){ /* usage example: data-mcs-theme="minimal" */
							o.theme=htmlDataTheme;
							_theme(o); /* theme-specific options */
						}
						
						_pluginMarkup.call(this); /* add plugin markup */
						
						$("#mCSB_"+d.idx+"_container img:not(."+classes[2]+")").addClass(classes[2]); /* flag loaded images */
						
						methods.update.call(null,$this); /* call the update method */
					
					}
					
				});
				
			},

**Comment by yi2020** [comment]
OK, I managed to cause the code to be called by adding the mCustomScrollbar class to the UL:

<div class="map_container" style="line-height: normal">
            
            <div id="alerts_list">
                <div class="inner">
                    <div class="bg"></div>
                    <div class="heading">
                        <span class="time">Time</span>
                        <span class="title">Alerts title</span>
                        <span class="device">Device</span>
                    </div>
                    <ul  class="mCustomScrollbar"></ul>
                </div>
            </div>
            <div id="map"></div>
            <div class="copyright"><a href="http://www.indeni.com/indeni-insight" target="_blank" style="text-decoration: none">Powered by <span style="text-decoration: underline">indeni Insight</span></a></div>
            <div class="loader" style="background: #fff; width: 400px; padding: 10px; box-shadow: 0 5px 10px #000; color: black; text-shadow: 0 0 0px black; font: 24px 'Roboto Condensed', sans-serif">Data loading, please wait...</div>
        </div>

Now though, something else weird is happening. See the attached screenshots. Look at the value I'm watching on the right - selecting all the elements with the mCustomScrollbar class (there's just one, a UL) and looking at the prototype of the selector.

While still in the init phase of the mCustomScrollbar plugin, you see that the mCustomScrollbar function is part of the prototype. However, later on, when we get to the window.load code that calls it, it's no longer there. How can it be removed??

![screenshot 2015-08-07 at 15 44 49](https://cloud.githubusercontent.com/assets/10076447/9147415/ac65ebe0-3d1b-11e5-9f28-718919d7a00b.png)

![screenshot 2015-08-07 at 15 45 06](https://cloud.githubusercontent.com/assets/10076447/9147417/b07bae36-3d1b-11e5-877f-482a8e264cbb.png)

![screenshot 2015-08-07 at 15 45 50](https://cloud.githubusercontent.com/assets/10076447/9147420/b6ff2ca6-3d1b-11e5-97c8-6ea68dd598a2.png)

![screenshot 2015-08-07 at 15 45 57](https://cloud.githubusercontent.com/assets/10076447/9147423/bbf21188-3d1b-11e5-8c3e-0de0face847a.png)

**Comment by yi2020** [comment]
I found out what it is! Another JS, mc-validate.js, that was called at the bottom of the page, would load after the mCustomScrollbar plugin and reset the jQuery. Solved.
