### ISSUE TITLE
How set callback of scrollTo method ?

### ISSUE THREAD

**Issue by cawa-93** [malihu/malihu-custom-scrollbar-plugin#339]
Code example:
```javascript
$('button').on('click', function(){
    // some code
    $('div').mCustomScrollbar("scrollTo", $('button').parent('div'));
    $('textarea').focus(); // this line must start when scrollTo method has been complete
});
```
How to perform the specified string after the method finishes scrolling?
To use the global callback is not suitable, as I only need to handle the case. The method used in other parts of the code, and there the handler is not needed.
There may be a way to use ```jquery.when()``` or ```jquery.promise()``` for this?
At the moment came up with just such a solution:
```javascript
$('button').on('click', function(){
    // some code
    $('div').mCustomScrollbar("scrollTo", $('button').parent('div'));
    setTimeout(function () {
        $('textarea').focus(); // this line must start when scrollTo method has been complete
    });
});
```

**Comment by malihu** [comment]
There's no specific callback for individual scrollTo method calls, as all callbacks are handled globally via the callbacks parameter. **There is a way though to differentiate a scrollTo method callback**, by using the `$(this).data("mCS").trigger` object ([info](http://manos.malihu.gr/jquery-custom-content-scroller/4/#faq-2)). 

In your case for example, you can set your callbacks like this: 

```
$(selector).mCustomScrollbar({
	callbacks:{
		onScroll:function(){
			if($(this).data("mCS").trigger==="external"){
				//scrollTo method callback functions
				$("textarea").focus();
			}else{
				//standard callback functions
			}
		}
	}
});
```

so `$("textarea").focus();` will trigger only after a scrollTo method scroll event. 

Now, if you have multiple scrollTo method calls and want to make it specific to this button, you can do: 

```
$(selector).mCustomScrollbar({
	callbacks:{
		onScroll:function(){
			if($(this).data("mCS").trigger==="external"){
				//scrollTo method callback functions
				if($("button").is(":focus")){
					//button callback functions (if button has focus it was clicked)
					$("textarea").focus();
				}
			}else{
				//standard callback functions
			}
		}
	}
});
```

and your button click event would simply be: 

```
$("button").on("click",function(){
    //some code
    $(selector).mCustomScrollbar("scrollTo", $("button").parent("div"));
});
```
