### ISSUE TITLE
Inline style violates CSP

### ISSUE THREAD

**Issue by Nadoedalo** [malihu/malihu-custom-scrollbar-plugin#347]
It seems like a lot of hardcode inside of lib should be fixed by either using ".css" jquery method or getting them inside of theme stylesheet because there are problems with Content Security Policy - this plugin requires unsafe-inline directive for styles.
Mostly is is in  "_pluginMarkup=function(){ " and few other places. Is there really any need for those ones?
PS I'm going to fix that, just reporting.

**Comment by ikeagold** [comment]
:+1: for that and CSP..

**Comment by Nadoedalo** [comment]
https://github.com/malihu/malihu-custom-scrollbar-plugin/pull/348
This pull has all of the required fixes but I haven't done minified version, so the issue is closed.
