### ISSUE TITLE
ScrollTo -= pixel amount create an error.

### ISSUE THREAD

**Issue by alexelash** [malihu/malihu-custom-scrollbar-plugin#351]
Hey, I could possibly be making a noob mistake. I'm trying to get mCustomScrollbar to scroll 80 pixels more every time you click on a specific button. From what I gathered from your demo, you can do so with -=(integer), so I wrote this code below:

<pre>
$('a#the_button').on('click', function(e) {
    e.preventDefault();
   $('#the_div').mCustomScrollbar('scrollTo', -=80);
});

</pre>

But that causes an error, of course. Am I missing something? This is the error:

<pre>Uncaught SyntaxError: Unexpected token -=</pre>

**Comment by alexelash** [comment]
OOPS caught my error by looking at the docs again. I didn't see the purple text pop up when you click (http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/scrollTo_demo.html#). Sorry about that!

**Comment by alexelash** [comment]
Okay, nevermind, I just tried what was in the docs and it created a new error:
<pre>
Uncaught Error: Syntax error, unrecognized expression: -=80
</pre>

My updated code per the docs is:
<pre>
$('a#the_button').on('click', function(e) {
    e.preventDefault();
   $('#the_div').mCustomScrollbar('scrollTo', '-=80');
});
</pre>

**Comment by malihu** [comment]
`$('#the_div').mCustomScrollbar('scrollTo', '-=80');` should work as the code is correct. If you can post the rest of your code (or a link) I might be able to help.

**Comment by alexelash** [comment]
So I actually figured this out... and it's fortunately still basically my error. I had an older version of your plugin on this website (I was actually just making a simple update). I suppose that it was old enough that maybe the feature above wasn't yet an option. All good now—I was able to get this work.

Thanks!
