### ISSUE TITLE
No events?

### ISSUE THREAD

**Issue by bensampaio** [malihu/malihu-custom-scrollbar-plugin#356]
Is there no way to use the callbacks as events? I mean something like this:

```js
let $element = $('#myScrollableElement').mCustomScrollbar();

$element.on('scroll', () => {
  // Make stuff
});
```

If not, I think that would be a great improvement... I may want to set multiple scroll events on the same element and that's functionality that jQuery already provides... I looked for this everywhere in the plugin page and couldn't find any information, so I'm sorry if it is actually possible.

**Comment by malihu** [comment]
No (at least for now). I'll consider this for a future release, thanks for the suggestion! 
I don't know exactly what you want to do but you can set multiple events via plugin's `callbacks` (meaning the functionality is there).

**Comment by bensampaio** [comment]
Yeah I think I'll do that, but it would be better if the functionality was already there. That's why I decided to ask first. Looking forward to see those events implemented! :p
