### ISSUE TITLE
How to disable animation when use scrollTo

### ISSUE THREAD

**Issue by zupaazhai** [malihu/malihu-custom-scrollbar-plugin#363]
follow the topic, I would like to disable animation when use scrollTo for move scroll to new position. How i can custom?

thank.

**Comment by malihu** [comment]
Set `scrollTo` method's `scrollInertia` option to `0`. For example: 

```
$(selector).mCustomScrollbar("scrollTo","bottom",{
    scrollInertia:0
});
```

[more info](http://manos.malihu.gr/jquery-custom-content-scroller/#methods-section-scrollTo)

**Comment by zupaazhai** [comment]
thank. it's helpful
