### ISSUE TITLE
setHeight: "80" does not set 80%

### ISSUE THREAD

**Issue by onet4** [malihu/malihu-custom-scrollbar-plugin#365]
Hello,

> setHeight: false 
> Set the height of your content (overwrites CSS height), value in pixels (integer) or percentage (string). 

It seems setting a string value does not result in percentage but pixel. 

```JavaScript
				$("#content-1").mCustomScrollbar({
					theme:"minimal",
                    setHeight: "80",
				});
``` 
This sets the container to 80px. I expected it would be 80%. Am I missing something? (using v3.1.1)

**Comment by malihu** [comment]
Set it to `"80%"`

**Comment by onet4** [comment]
Got it. Thank you.
