### ISSUE TITLE
Scrolling Behavior

### ISSUE THREAD

**Issue by russ-ab** [malihu/malihu-custom-scrollbar-plugin#379]
Hi,

I'm build a chat application using mCSB attached to the content.
When it receive a new message, that message is appended to the body and a scroll to bottom is executed.
That works fine when the window is showing, but when the user is using another tab or another application the scrolling doesn't work.

That behavior only happens on FIREFOX, by the way, sometimes the scroll works sometimes not.
In CHROME everything is fine. IE not tested.

I made a Fiddle to try to simulate the scenario: http://jsfiddle.net/3xg9w2o5/9/

**Comment by malihu** [comment]
This is intended behavior. This is what should happen: 

* When browser chat tab is active/visible scroll to bottom happens normally (set by your interval). 
* When the user switches to another tab/window/application, the chat tab becomes hidden and animations become zero. 
* When the user switches back to the chat tab, it becomes visible again and **scroll to bottom happens on the next immediate interval**. 

This is what happens when I test your fiddle in latest Firefox (42). Is this also what you see? 

Is there a case where you'd want constant scrolling animation on hidden tab?

**Comment by russ-ab** [comment]
Yes this is what I'm seeing too in Firefox (39).
In Chrome (44) scrolling happens even in not visible window (or redraw instantly when window get focus).

When a new message arrives the scroll needs to go to bottom even if the user is not in the tab.

I cannot wait the next interval to redraw/scroll the content because it's a long polling request. So if the next message arrives in next 20 seconds there's a gap with invisible content in the body.

Current case: User switch tab, message arrive, user comeback to tab, **content invisible and/or not scrolled**, message arrive, content visible and scrolled.

Wanted case: User switch tab, message arrive, user comeback to tab, **content visible and scrolled**, message arrive, content visible and scrolled.

**Comment by malihu** [comment]
I think you should use the page visibility api to trigger scroll to bottom when tab gets visible. 
For example: 

```
//-----
//polyfill
if(typeof document.hidden!=="undefined"){ //unprefixed
  hidden="hidden";
  visibilityChange="visibilitychange";
}else{ //prefixed
  var pfx=["webkit","moz","ms","o"];
  for(var i=0; i<pfx.length; i++){
    if(typeof document[pfx[i]+"Hidden"]!=="undefined"){
      hidden=pfx[i]+"Hidden";
      visibilityChange=pfx[i]+"visibilitychange";
    }
  }
}
//event
document.addEventListener(visibilityChange, function(){
  if(!document[hidden]){ //if tab is visible trigger method
    $('.scroll').mCustomScrollbar("scrollTo", "bottom");
  }
}, false);
//-----
```

Can you test it and let me know?

**Comment by russ-ab** [comment]
Yes! It worked as expected.

Thank you Malihu!

**Comment by malihu** [comment]
You're welcome :)
