### ISSUE TITLE
Invalid XML, easy fix

### ISSUE THREAD

**Issue by chinoto** [malihu/malihu-custom-scrollbar-plugin#383]
When calling .mCustomScrollbar() on a XHTML page, it triggers this error: "Uncaught SyntaxError: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document."

On line 872 inside the .wrapInner() call, the dir attribute isn't quoted, add quotes and it's fixed.

**Comment by malihu** [comment]
Thanks for the feedback! I pushed the fix in [3.x branch](https://github.com/malihu/malihu-custom-scrollbar-plugin/tree/3.x). I'll include it (among others) in the next release (3.1.4).

**Comment by malihu** [comment]
This is fixed in 3.1.4
