### ISSUE TITLE
Scrollbar position bottom by default

### ISSUE THREAD

**Issue by artsx** [malihu/malihu-custom-scrollbar-plugin#409]
Hello, there would be a solution for the scrollbar begins by default at the bottom of content?
The "scroll", "bottom" has an animated effect, I would like by default the bar is down

Best Regards,

**Comment by fwhenin** [comment]
+1

**Comment by malihu** [comment]
You can set `scrollInertia` option to `0` on the _scrollTo_ method ([see "Method options" in _scrollTo_ method section](http://manos.malihu.gr/jquery-custom-content-scroller/#methods-section-scrollTo)) to make scrolling instant (no animation). For example: 

```
$("#your-elem").mCustomScrollbar("scrollTo","bottom",{scrollInertia:0});
```

There are multiple ways to start scrolling from the bottom at initialization:  

**1. Chaining _scrollTo_ method**

```
$("#your-elem").mCustomScrollbar({
	//your options...
}).mCustomScrollbar("scrollTo","bottom",{scrollInertia:0});
```

**2. Using [`setTop` option](http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-setTop)**

```
$("#your-elem").mCustomScrollbar({
	setTop:"-999999px"
});
```

**Comment by romuloinnocencio** [comment]
Why it starts in bottom, why not start normally in top 0?

**Comment by buggyman** [comment]
In my case it was start from bottom because I place initialization code to method "open" of $(...).dialog() plugin with dinamic content. So, updateOnContentResize was triggered after $(...).mCustomScrollbar() initialized.
I move $(...).mCustomScrollbar() code to the end of loading content and issue was resolved.

ADD: I'm use version: 2.8.2 of mCustomScrollbar

**Comment by xeroxstar** [comment]
**## romuloinnocencio** for chat you need to start at bottom or maybe other applications is there that has to start at the bottom, but for sure the chat app always start at bottom.  Anyway, `$("#your-elem").mCustomScrollbar("scrollTo","bottom",{scrollInertia:0});` give me error `"Uncaught TypeError: n.easing[this.easing] is not a function" `

**Comment by krystyna93** [comment]
I have a custom scrollbar on my body, and one on a div with the scrollTo at the bottom. My issue is that the scrollTo option makes my body scrollbar scrollTo at the bottom, even though I have assigned a class to the specific div. 

Any ideas of how I can stop it from targeting the body scrollbar as well?

**Comment by dimonshut** [comment]
```
// custom scrollbar
var $cartBlock = $('.catalog-filter-scroll-block');
if ($cartBlock.height() >= 250) {
	$cartBlock.mCustomScrollbar({
		theme:"dark",
		/*autoHideScrollbar:true,*/
		scrollInertia:0,
		setTop: 0,
		setHeight: 300,
		callbacks:{
		    onInit:function(){
		    	setTimeout(function() {
		      		$cartBlock.mCustomScrollbar('scrollTo','first');
		      	}, 500);
		    }
		}
	});
}
```
