### ISSUE TITLE
Can't scroll horizontally on iOS 9.3.1

### ISSUE THREAD

**Issue by Blackeye** [malihu/malihu-custom-scrollbar-plugin#416]
Hej malihu!

I’ve updated to 3.1.3 of your plugin to get the fix to be scrollable horizontally, if the slider is vertically (see your comment here: http://stackoverflow.com/a/26496368/4323473). This works on good on the samsung internet browser, the sailfish chrome and other browsers. But I didn’t get it working on the newest iOS version (9.3.1). Can you confirm this problem and do you have an idea how to fix it?

Yours,
Thomas

**Comment by tefdos** [comment]
Hi, I have the same problem on 9.3.1 - the slider works, but I can't scroll the screen vertically when the touch starts on the slider. It worked on iOS 9.2.1 though.

**Comment by yukku0423** [comment]
on iOS 9.3.x, I have the problem. Applying the changes can resolve this. https://github.com/mlavrinenko/malihu-custom-scrollbar-plugin/commit/be6ad75c81054560465d04e26cbccef1bbdc7fcc

**Comment by Blackeye** [comment]
Thx yukku0423. The fix is working!

Nevertheless I hope that we get a new version of the plugin :)

**Comment by malihu** [comment]
@Blackeye 

Yes of course. I'll add a fix for this asap on 3.x and on the next version (3.1.5).

**Comment by malihu** [comment]
I've just released version 3.1.5 which includes the fix. I've tested it on latest iOS (9.3) and it works. If you find any issue let me know.
