### ISSUE TITLE
make it so you can move up and down with keyboard

### ISSUE THREAD

**Issue by terrafrost** [malihu/malihu-custom-scrollbar-plugin#42]
First, let me just say that I love this plugin! Am currently having one small intermittent hard to isolate issue that's probably use-case specific that I emailed you aboutt but other than that it's working great!

Anyway, I think it'd be great if you could tab up or hit the arrow up button or tab down / hit arrow down to change your position within the scrollbar. I do it all the time on sites using the browsers scroll bar and think it'd be useful if it could be done with this scrollbar as well.

Thanks!

**Comment by rishiVickey** [comment]
@malihu  keyboard scroll is not working when we are not hovering the div. is there any way we can do this without hovering

$(elementId).hover(function () {
        $(document).data({ "keyboard-input": "enabled" });
        $(this).addClass("keyboard-input");
    }, function () {
        $(document).data({ "keyboard-input": "disabled" });
        $(this).removeClass("keyboard-input");
    });
    $(document).keydown(function (e) {
        if ($(this).data("keyboard-input") === "enabled") {
            var activeElem = $(".keyboard-input"),
                activeElemPos = Math.abs($(".keyboard-input .mCSB_container").position().top),
                pixelsToScroll = 60;
            if (e.which === 38) { //scroll up
                e.preventDefault();
                if (pixelsToScroll > activeElemPos) {
                    activeElem.mCustomScrollbar("scrollTo", "top");
                } else {
                    activeElem.mCustomScrollbar("scrollTo", (activeElemPos - pixelsToScroll), { scrollInertia: 400, scrollEasing: "easeOutCirc" });
                }
            } else if (e.which === 40) { //scroll down
                e.preventDefault();
                activeElem.mCustomScrollbar("scrollTo", (activeElemPos + pixelsToScroll), { scrollInertia: 400, scrollEasing: "easeOutCirc" });
            }
        }
    });
