### ISSUE TITLE
Loading external resources

### ISSUE THREAD

**Issue by AmitMY** [malihu/malihu-custom-scrollbar-plugin#422]
I don't understand why does the distribution file loads a new file via http - 
http://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js?_=1464197036975

Especially when some apps requires offline usage.

Is there a way to fix it, and instead just load jquery mousewheel from an assets folder into the minified file, or just an npm dependency?

Or, load it only if mousewheel is not already loaded, so Ill load jquery mousewheel separately.

And finally, can the NPM module have the minified files as well?

Great library nonetheless!

**Comment by malihu** [comment]
I'll probably add the jquery.mCustomScrollbar.concat.min.js in npm. 

If you load jquery mousewheel **before** jquery.mCustomScrollbar.js, the mousewheel will not load.
