### ISSUE TITLE
mCustomScrollbar & Bootstrap Modal

### ISSUE THREAD

**Issue by t3chn0r** [malihu/malihu-custom-scrollbar-plugin#43]
I'm trying to implement mCustomScrollbar in a Bootstrap Modal window without luck so far.

I have a simple DIV with a max-height of 250px and overflow: hidden. If I don't call mCustomScrollbar I get the browsers' native scrollbars and everything works fine.

If I call mCustomScrollbar then the browsers' native scrollbars disappear and not even the mousewheel works. I put the same exact content outside the modal and mCustomScrollbar works fine.

Has anybody seen the same issue?

By the way, I'm using the latest versions of jQuery and Bootstrap.

_edit_: I just found out that if I do an "Inspect element" in Firefox inside the list the custom scroll bar appears and I can scroll with the mousewheel or dragging the dragger. What is "Inspect element" really doing that makes the scrollbar show up? I'm so confused right now...

**Comment by Deepak13245** [comment]
Always apply mCustomScrollbar to the parent node of element.

**Comment by svishwash123** [comment]
i have the same , problem but , i have a parent container which contains horizontal scroll and inside the parent container there is 5 block which has scroll, and modal is opening but it is opening very slowly, its happening only in mac chrome
