### ISSUE TITLE
deactivate on mobile

### ISSUE THREAD

**Issue by dstN** [malihu/malihu-custom-scrollbar-plugin#437]
is there any possibility to deactivate the scrolling on viewports below 768px? because after that my layout changes and the scrolling is not needed anymore.

**Comment by malihu** [comment]
You could use the `destroy` method like this: 

```
(function($){
	$(window).resize(function(){
		if($(this).width()>768){
			$(selector).mCustomScrollbar(); //apply scrollbar with your options 
		}else{
			$(selector).mCustomScrollbar("destroy"); //destroy scrollbar 
		}
	}).trigger("resize");
})(jQuery);
```

Is this what you need?

**Comment by dstN** [comment]
something like that yes. but i made it with an other approach now:

```
var handleMediaChange = function (mediaQueryList) {
        if (mediaQueryList.matches) {
            
        }
        else {
            $(".googlemap .gmapoverlay").mCustomScrollbar({
                theme: "minimal" 
            });
        }
    }
    
    var mediaQueryMatch = window.matchMedia("(max-width: 767px)");
    mediaQueryMatch.addListener(handleMediaChange);
    handleMediaChange(mediaQueryMatch);
```

**Comment by malihu** [comment]
Yes `window.matchMedia` is better as it matches CSS media queries. There are also alternative ways to detect mobile/phone, for example [web.wurfl.io](https://web.wurfl.io) or [mobile-detect.js](http://hgoebl.github.io/mobile-detect.js/).

**Comment by malihu** [comment]
I've also added more info and examples in plugin's [FAQ](http://manos.malihu.gr/jquery-custom-content-scroller/4/#faq-14)

**Comment by imarks-saisudhakar** [comment]
page is not moving when scroll bar is reached end of div in android browser.

**Comment by mehdiagharlou** [comment]
@imarks-saisudhakar @malihu 
I have also that issue, when scrollbar is reached back to top, page not scrolling up.

**Comment by RickHocutt** [comment]
@mehdiagharlou I had the same issue and am now using this method to disable the script for mobile devices (limited testing but seems to work great):
```javascript
var isMobile = {
	Android: function() {
		return navigator.userAgent.match(/Android/i);
	},
	BlackBerry: function() {
		return navigator.userAgent.match(/BlackBerry/i);
	},
	iOS: function() {
		return navigator.userAgent.match(/iPhone|iPad|iPod/i);
	},
	Opera: function() {
		return navigator.userAgent.match(/Opera Mini/i);
	},
	Windows: function() {
		return navigator.userAgent.match(/IEMobile/i);
	},
	any: function() {
		return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
	}
};

if(!isMobile.any()) {
	// Initialize custom scrollbar
	$(".selector").mCustomScrollbar({
		autoHideScrollbar: true
	});
}
```
