### ISSUE TITLE
iOS (Chrome, Safari): Disabled scrollbar doesn't scroll

### ISSUE THREAD

**Issue by DriftingSteps** [malihu/malihu-custom-scrollbar-plugin#440]
Any `div` with less content than the defined height is supposed to hide the scrollbar by default. And in my case, it works as it is supposed to. In iOS browsers (Safari, Chrome), the scrollbar does hide, but the container which holds the scrollbar class cannot be swiped up or down. I have the website online where the scrollbar is supposed to be - [http://realjuice.rajendra.info.np/product/real-burrst-apple](http://realjuice.rajendra.info.np/product/real-burrst-apple)

Is this solely a CSS issue or a js issue?

**Comment by malihu** [comment]
Your js code is not correct. Change: 

```
(function($){
	$(window).on("load",function(){
	$(".scrollbar-inner").mCustomScrollbar({
	theme: "minimal-dark",
	scrollbarPosition: "outside",
	scrollInertia: 500
	});
	});
})(jQuery);

  (function($){
    $(window).resize(function() {
      if($(this).width()>768){
        $(selector).mCustomScrollbar(); //apply scrollbar with your options 
      } else {
        $(selector).mCustomScrollbar("destroy"); //destroy scrollbar 
      }
    }).trigger("resize");
  })(jQuery);
```

to: 

```
  (function($){
    $(window).resize(function() {
      if($(this).width()>768){
        $(".scrollbar-inner").mCustomScrollbar({
		theme: "minimal-dark",
		scrollbarPosition: "outside",
		scrollInertia: 500
	}); 
      } else {
        $(".scrollbar-inner").mCustomScrollbar("destroy"); 
      }
    }).trigger("resize");
  })(jQuery);
```

Let me know

**Comment by DriftingSteps** [comment]
Hi, thank you very much for the solution. It works perfectly, as does your plugin.

Thanks again :)
