### ISSUE TITLE
Page jumps back to the top when scrolling with mouse wheel

### ISSUE THREAD

**Issue by SaraTerry94** [malihu/malihu-custom-scrollbar-plugin#441]
Hello,

If you click on a link on my site, then use the mouse wheel to scroll up the page jumps to the top, instead of scrolling smoothly. I know the issue is with the plugin because when I removed it the scrolling worked, although it caused issues elsewhere, so ideally i'd like to keep the plugin but fix this issue.

The site can be found here: http://www.kent.co.uk/test1/
The links are the images with text: 'Need to Know', 'What's on' and 'Find out more' 

I just updated the JS to the newest version as well but I am still experiencing the problem

Thank you

**Comment by malihu** [comment]
Hi, 

I can't reproduce this issue of jumping to the top. Does this happen on specific OS/browser/input device?

**Comment by SaraTerry94** [comment]
Hi, 

Thank you for your reply. I managed to fix it by adding

$(document).on("click","a[href^='#']",function(e){
  var href=$(this).attr("href"),target=$(href).parents(".mCustomScrollbar"); 
  if(target.length){
    e.preventDefault();
    target.mCustomScrollbar("scrollTo",href);
  }
});

Simple I know!

**Comment by malihu** [comment]
Great :)
