### ISSUE TITLE
Get Current Scroll When User Interacting ?

### ISSUE THREAD

**Issue by Noobknight** [malihu/malihu-custom-scrollbar-plugin#461]
I'm newbie web developer. In page, I have three scrollbar and How do I know users are interacting with any scroll bars ?

**Comment by malihu** [comment]
You can use [plugin's callbacks](http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-callbacks-onCreate). 

[Example](https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/examples/callbacks_example.html) 
[Demo](http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/callbacks_example.html)
