### ISSUE TITLE
How to show arrow buttons.

### ISSUE THREAD

**Issue by ClarusDignus** [malihu/malihu-custom-scrollbar-plugin#463]
Should the arrow buttons show by default?

I've tried various themes but I'm not seeing the button.

Am I overlooking basic CSS requirements for my containers or is this a configuration concern?

Thanks for a great plugin!

**Comment by malihu** [comment]
Arrow buttons do not show by default. You need to enable them via the [`scrollButtons: enable` option](http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-scrollButtons-enable): 

```
$(selector).mCustomScrollbar({
  scrollButtons:{
    enable:true
  }
});
```

Also, make sure you have the [mCSB_buttons.png](https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/mCSB_buttons.png) on the same dir with plugin's stylesheet (jquery.mCustomScrollbar.css).

**Comment by ClarusDignus** [comment]
Thanks and apologies, I should have taken greater care reviewing the [configuration parameters](http://manos.malihu.gr/jquery-custom-content-scroller/) that have been well documented.

I'm immensely enjoying the ease of use this plugin as well as the broad variety of beautifully designed scroll-bars styles that come bundled with the plugin.

Thanks!

**Comment by BatIronMan007** [comment]
I am trying to add custom arrow button image in the css. But unable to do so. Request you lemme know how this is done.

.mCSB_buttonDown{
    border: 1px solid #898888;
    background-position: center;
    background-repeat: no-repeat;
    background-size: 18px 18px;
    background-image: url('../Images/Icons_6x/Down-Grey.png'); 
}

Thanks.

**Comment by senyqy** [comment]
> Arrow buttons do not show by default. You need to enable them via the [`scrollButtons: enable` option](http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-scrollButtons-enable):
> 
> ```
> $(selector).mCustomScrollbar({
>   scrollButtons:{
>     enable:true
>   }
> });
> ```
> 
> Also, make sure you have the [mCSB_buttons.png](https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/mCSB_buttons.png) on the same dir with plugin's stylesheet (jquery.mCustomScrollbar.css).

It doesn't work
