### ISSUE TITLE
Not Showing on Electron JS

### ISSUE THREAD

**Issue by pawanagre** [malihu/malihu-custom-scrollbar-plugin#473]
I am using this custom-scrollbar-plugin in Electron JS, but it is not working in this environment and showing error as : 
```
angular.js:12477 TypeError: $(...).mCustomScrollbar is not a function
    at Object.scrollBar [as malihuScroll]
```
It is working properly with all browsers but not with Electron JS (http://electron.atom.io)
![error](https://cloud.githubusercontent.com/assets/23329465/20088563/0431eed8-a5a7-11e6-9873-9c4a884e39e4.png)

**Comment by lhttjdr** [comment]
Perhaps you need something like 
```
var $ = require('jquery');
require('malihu-custom-scrollbar-plugin')($);
```
where `($)` is the key point.

**Comment by pawanagre** [comment]
@lhttjdr Thanks for your solution. It really worked for me.
