### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by erichaus** [malihu/malihu-custom-scrollbar-plugin#487]
Hello,

I was hopeful after discovering this that I could use it in my ember app however when I init my `.scrollable` element which contains many child message elements (chat), it seems to set a `max-height` css attribute that makes the element unscrollable, and I don't see the custom scrollbar at all although I do notice it has rendered a bunch of stuff in the dom...

Any suggestions?

![image](https://cloud.githubusercontent.com/assets/230757/21107386/597575c2-c046-11e6-8272-8e99c2a36bd1.png)

**Comment by Mmatiasn** [comment]
+1
Having a similar issue where the dom is manipulated but nothing happens.
