### ISSUE TITLE
malihu-custom-scrollbar-plugin is not working in SPFx

### ISSUE THREAD

**Issue by VidhiBartariya** [malihu/malihu-custom-scrollbar-plugin#523]
Hi ,

I have  a requirement where i have to use "custom-scrollbar" with my spfx webpart so i have used "malihu-custom-scrollbar pluging".
configured using  "**npm install malihu-custom-scrollbar-plugin"**
after this I have call it in my webpart.ts file:
**require('malihu-custom-scrollbar-plugin');**
and typed code on document.ready :
$(document).ready(function () {
                try {
                    $('.eventSection').mCustomScrollbar();
                } catch (e) {
                    console.log("Error message :" + e.message);
                }
            });

but while building it it's giving error like:
**## Error - typescript - src\webparts\eventSection\app\EventHomeController.ts(44,39): error TS2339: Property 'mCustomScrollbar' does not exist on type 'JQuery'.**

let me know if i need to configure anything else?
Or also let me know if we can use malihu-custom-scrollbar-plugin  or not?

**Comment by guibot17** [comment]
I have the same error in my Angular 2 project
