### ISSUE TITLE
TypeError: $(...).mCustomScrollbar is not a function

### ISSUE THREAD

**Issue by Wayne529** [malihu/malihu-custom-scrollbar-plugin#576]
hey!This plugin is very well,but occasionally get something wrong.I use Seajs loading it,most of the time,it can work correctly in Chrome browser,but sometimes it throw the error:$(...).mCustomScrollbar is not a function.I really can not find the reason which cause the error.Unfortunately,if I use Firefox browser,the error is appears inevitably,it absolutely throw this error:TypeError: $(...).mCustomScrollbar is not a function.And I find some solution in issues,I had tried use '$(window).load(function(){})' instead of '$(function(){})',but it doesn't work.Hope your response,thank u!
![qq 20171114150352](https://user-images.githubusercontent.com/13690232/32769395-ad7813e0-c956-11e7-95e2-90ad0096bd0e.jpg)

**Comment by rodrigoeidelvein** [comment]
Hi @Wayne529 , I was having the same problem in Firefox. I think the error occours because the script is being executed before the elements being loaded. So I made a pretty ugly workaround by setting a little timeout to wait the elements.

**Comment by Kyle772** [comment]
Don't set a timeout. 

Fix the order that your js is being loaded. You need to have it as jQuery -> mCSB -> Init js
You can use async and await if you need to fine tune how things are loaded or you can set up requirejs on your project.

Typically you should be able to get this set up properly without using requirejs but sometimes with larger projects you simply need to get the order of js loading consistent. 

I'd place all your scripts at the end of the body so A) the dom is loaded when they're initialized and B) so you can separate global scripts from page specific scripts. 

Here is what mine looks like:
```
<head>
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-
    DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
</head>
<body>
    <script src="/js/lodash.core.js"></script>
    <script src="/js/malihu-custom-scrollbar-plugin-master/jquery.mCustomScrollbar.concat.min.js">
    </script>
    <script src="/js/base.js"></script>
</body>
```
 jQuery -> mCSB -> Init js

Hope this helps!

EDIT: Just looked up seajs. Same order but you need to be setting it within that library. Haven't used that before so you're on your own but this advice should help you get in the right direction.

**Comment by pavanbhat1999** [comment]
@Wayne529  I still have the issue have you found the solution
