### ISSUE TITLE
scrollbar doesn't show up when the content is added dynamically to the inside div.

### ISSUE THREAD

**Issue by cmayankc** [malihu/malihu-custom-scrollbar-plugin#65]
Hi Malihu,
I am facing an issue using custom scrollbar in one of my pages. Below is my html

<pre>
<code>
&lt;DIV id="content" style="float:left; height: 500px; width: 800px; margin: 20px; overflow: auto; border: 2px solid; background: #333; color: #999; border-radius: 5px;"&gt;
    &lt;DIV id="divtext" style="float:left; width:550px; border:solid 1px gray; margin: 5px;"&gt;
             &lt;!-- some content that fits in the outer div height --&gt;
        &lt;/DIV&gt;
&lt;/DIV&gt;
</code>
</pre>

now, if I load some large content in the inside div, the scrollbar doesn't show up on the outside div. The html default scrollbar works fine.

this is how i use the custom scroller:

<pre>
<code>
$('#content').mCustomScrollbar({
                theme:"light",
                scrollButtons:{
                        enable:true
                }
            });
</code>
</pre>

any ideas?

**Comment by degeta10** [comment]
> You can set the updateOnContentResize option parameter to true on the initial call to auto-call the update method each time the content changes:
> 
> $('#content').mCustomScrollbar( {
> theme:"light",
> scrollButtons:{
> enable:true
> },
> scrollInertia:0,
> advanced:{
> autoScrollOnFocus: false
> updateOnContentResize: true
> },
> });

There is a comma missing in the line
`autoScrollOnFocus: false`

So this is the result ,
```
$("#content").mCustomScrollbar({
        theme: "light",
        scrollButtons: {
            enable: true
        },
        scrollInertia: 0,
        advanced: {
            autoScrollOnFocus: false,
            updateOnContentResize: true
        },
    });
```
