### ISSUE TITLE
With jQuery 3.5.0 and higher a visual problem occurs

### ISSUE THREAD

**Issue by luciminea** [malihu/malihu-custom-scrollbar-plugin#652]
If I use jQUery 3.5.0 or above, the plugin works, but the scrollbar container, that is supposed to be fixed and occupy all height of the element, is now scrolling with the scrollbar, just under the scrollbar.

I've downgraded to jQuery 3.4.1 and it's working as supposed.

I've placed two pictures, one with the 3.4.0 and the other with the 3.5.0.

This is the 3.5.0 behaviour

![abnormal-3d](https://user-images.githubusercontent.com/7003625/81193785-8838b080-8fc4-11ea-8b59-c9e40725a4c1.jpg)

This is the 3.4.1 behaviour 

![normal-3d](https://user-images.githubusercontent.com/7003625/81193790-88d14700-8fc4-11ea-8fcd-c02674791578.jpg)

**Comment by nns52k** [comment]
The horizontal scrollbar has the same problem.

**Comment by jinixx** [comment]
Fixed it on my fork. Feel free to use. 
[https://github.com/jinixx/malihu-custom-scrollbar-plugin/](https://github.com/jinixx/malihu-custom-scrollbar-plugin/)

**Comment by luciminea** [comment]
Yes, it's working correctly now ! Thank you very much !

**Comment by gvereido** [comment]
@jinixx thank you for the fix - it fixed this vertical scrollbar issue. 
It seem like new issue created with the horizontal scrollbar. 
First - left and right buttons disappeared. Width and max-width are calculated wrong.
Second - the horizontal scrollbar drawn inside the div of the vertical scrollbar.

The code looks like this:

`<div id="mCSB_2_scrollbar_vertical" class="mCSB_scrollTools mCSB_2_scrollbar mCS-dark-3 mCSB_scrollTools_vertical" style="display: block;">`
`	<a href="#" class="mCSB_buttonUp" style="display: block;"/>`
`	<div class="mCSB_draggerContainer">`
`		<div id="mCSB_2_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 30px; display: block; height: 76px; max-height: 723px; top: 0px;">`
`			<div class="mCSB_dragger_bar" style="line-height: 30px;"/>`
`		</div>`
`		<div class="mCSB_draggerRail"/>`
`		<div id="mCSB_2_scrollbar_horizontal" class="mCSB_scrollTools mCSB_2_scrollbar mCS-dark-3 mCSB_scrollTools_horizontal" style="display: block;">`
`			<div class="mCSB_draggerContainer">`
`				<div id="mCSB_2_dragger_horizontal" class="mCSB_dragger" style="position: absolute; min-width: 30px; display: block; width: 10px; max-width: 6px; left: -2px;">`
`					<div class="mCSB_dragger_bar"/>`
`				</div>`
`				<div class="mCSB_draggerRail"/>`
`			</div>`
`		</div>`
`	</div>`
`	<a href="#" class="mCSB_buttonDown" style="display: block;"/>`
`</div>`

**Comment by shakirmsr** [comment]
thanks, @jinixx. It worked
