### ISSUE TITLE
Don't require CSS height or max-height

### ISSUE THREAD

**Issue by ibc** [malihu/malihu-custom-scrollbar-plugin#68]
Currently `mCustomScrollbar()` requires the container div to have "height" or "max-height" CSS attribute. That's is not very cool in cases in which we don't want to set such attributes (i.e. when using the new W3C FlexBox model with "flex-direction: column" in which the divs can fill the entire vertical space of the main box).

Why is "height" or "max-height" CSS attribute required? why not get the height via jQuery `height()` method?

**Comment by westis** [comment]
Are there updates to this? I'm also trying to add custom scrollbars to flex items and running into the same issues as above. And these days flexbox is supported by most browsers.

**Comment by neesonqk** [comment]
Me too, can this post be reopened again, I'm also facing this problem now. @westis did you find any way to work it around?

**Comment by malihu** [comment]
In version 3.1.0 it should be much easier to apply the scrollbar on flexbox. 
I'll appreciate any feedback :)

**Comment by Uniphix** [comment]
I have issues with this, in fact this is causing problems and I am NOT using flexbox, in fact this is causing and breaking our site all over the place, because I am using max/min height, and in fact it is doing it without using any CSS.  ONe of the things I am using is max-height: 80vh; which is 80 viewheight...   So for me to make this not happen for us I have had to modify the source and comment that code out

**Comment by malihu** [comment]
@Uniphix Hello, Which plugin version are you using? Which part you had to comment out? Thanks!

**Comment by malihu** [comment]
In version 3.1.1 I've updated the code regarding element's with max-height , so you may want to check it with your page.

**Comment by ERobishaw** [comment]
I'm having good success with 3.1.3 using flexbox with all browsers except Safari.
With Safari, my container is set to:
```
flex: 1 1 100%;
max-width: 100%;
max-height: 100%;
box-sizing: border-box;
min-height:100%;
```
**Which results in the .mCustomScrollBox height at 0 in Safari.**

The style for this container is setting style="max-height:280px" (for example) as calculated. This works for everyone but safari. 
**For safari, it needs either min-height or height also set to this value (height:280px) for it to render correctly.**

Here's the fix:
```
						/* css flexbox fix, detect/set max-height */
						mCustomScrollBox.css("max-height","none");
						if (mCustomScrollBox.height() !== $this.height()) {
						    mCustomScrollBox.css("max-height",$this.height());
						    **mCustomScrollBox.css("height",$this.height());**
						}

```

**Comment by ERobishaw** [comment]
I've forked the above fix here:
https://github.com/malihu/malihu-custom-scrollbar-plugin/compare/3.x...ERobishaw:patch-1

**Comment by KingSora** [comment]
In your first answer you wrote following:
"You cannot have a scrollbar (any scrollbar, browser's or javascript) without specifying some kind of height limit."

Sadly this is not true, as you can see in this fiddle: https://jsfiddle.net/1h2pzevc/

I hope youre plugin will be able to support behaviors like this (e.g. height: auto and width: auto) in the future, they are really useful for responsive layouts.

Best reagrds!
