### ISSUE TITLE
Sometimes scrollbar doesn't appear, but if I put on fullscreen mode of the browser it appears

### ISSUE THREAD

**Issue by bitliner** [malihu/malihu-custom-scrollbar-plugin#83]
As the title says,
sometimes in my page the scrollbar doesn't appear, even if it shoul appear (the content is bigger than the body with the scrollbar).

But if I put my browser in fullscreen mode, then the scrollbar starts to appear, also when I put off the fullscreen mode.

**Comment by jyotisman** [comment]
$.ajax({
					type: "POST",
					data: { 'order_id' : orderId },					
					url: SITE_URL+'myaccount/myOrderDetails/',
					beforeSend: function() {
						//$("#ajax-loader").show();
						$("#order-detail-pop").removeAttr("style");	
					},
					complete:function() {
						//$("#ajax-loader").hide();
					},
					success: function(data) {
						
						$("#order-detail-pop").find("div.content").mCustomScrollbar("destroy");					
						$("#order-detail-pop").find("div.content").html(data);
						$("#order-detail-pop").show();
						$("#order-detail-pop h1 .reorder-button").attr("data-order", order);
						
						if ($("#order-detail-pop div.content").length > 0) {
							$("#order-detail-pop div.content").mCustomScrollbar({
								theme: "minimal",
								scrollInertia: 50
							});
						}
					}
				});	


You can use $("#order-detail-pop").find("div.content").mCustomScrollbar("destroy");	.
Which will destroy the event , which previously started.
