### ISSUE TITLE
Iframe scroller get stuck when mouse get outside the iframe

### ISSUE THREAD

**Issue by metallipultura** [malihu/malihu-custom-scrollbar-plugin#87]
There is a scroller inside an iframe.

1: you "left click" the scroller's dragger as if you want to scroll the content
2: you keep the button pressed, and get the mouse out of the iframe
3: you release the button

When you get the mouse back over the iframe, the dragger is stuck to the mouse as if it was clicked...

**Comment by mihai-varga** [comment]
Also you can't scroll when the mouse gets out of the iframe. To reproduce:
1. open http://jsfiddle.net/50bq01ca/
2. grab the scroll bar
3. get the mouse out of the iframe (the result box)
4. try to move it up and down as if you were scrolling

Thanks!

**Comment by malihu** [comment]
Try adding iframe's parent to [`releaseDraggableSelectors` option](http://manos.malihu.gr/jquery-custom-content-scroller/#plugin-data-advanced-releaseDraggableSelectors) on `mCustomScrollbar` function call. For example: 

```
$(selector).mCustomScrollbar({
    advanced:{ releaseDraggableSelectors: top.document }
});
```

**Comment by mihai-varga** [comment]
Thanks @malihu for your reply.
This does indeed work, but seems that only in Firefox.
And I can't reproduce it this time with jsfiddle due to some cross origin problems.

**Comment by malihu** [comment]
Ah yes I see. The draggable release does work everywhere but drag-scrolling gets interrupted outside of the iframe. I'll need to check this further as js events on iframes can be a bit of a pain... I'll make some tests and let you know.

**Comment by Avessalom1** [comment]
I experience the same issue, however my scenario is
1) i grab the scroll bar inside iframe1
2) i move the mouse to iframe2
3) i release the mouse
4) i move it back to iframe1 and i'm still dragging the bar
this problem exists even in firefox

**Comment by malihu** [comment]
I've just pushed an update on [3.x branch (development version)](https://github.com/malihu/malihu-custom-scrollbar-plugin/tree/3.x) which should fix the issues with iframes, so try it and let me know. 

@mihai-varga With this update you don't need to set `releaseDraggableSelectors` option as it's done automatically.

**Comment by Avessalom1** [comment]
Tried the updated version. The problem still exists.

**Comment by malihu** [comment]
@Avessalom1 The update will work for the parent document of the iframe. I'll try some tests with cross-iframes events and push an update if everything works. For now, you can simply release the draggable element via the `releaseDraggableSelectors` option, e.g.: 

`
$(selector).mCustomScrollbar({
    advanced:{ releaseDraggableSelectors: $(top.document).find("#your_iframe_id").contents()[0] }
});
`

**Comment by malihu** [comment]
Ok I've just pushed an update to [3.x](https://github.com/malihu/malihu-custom-scrollbar-plugin/tree/3.x). Re-download it and use the newly added `extraDraggableSelectors` option to set the iframe(s) selector to allow scrolling. 

For example, assuming the page contains 2 iframes with id attributes `iframe-1` and `iframe-2` 

`#iframe-1` code: 

```
$(selector).mCustomScrollbar({
	advanced:{ extraDraggableSelectors: $(top.document).find("#iframe-2").contents()[0] }
});
```

`#iframe-2` code: 

```
$(selector).mCustomScrollbar({
	advanced:{ extraDraggableSelectors: $(top.document).find("#iframe-1").contents()[0] }
});
```

**Comment by malihu** [comment]
Also, if you have more than 2 iframes, you can add the selectors simply like this: 

#iframe-1 `extraDraggableSelectors` value: 
`$(top.document).find("iframe:not(#iframe-1)").contents().get()`

#iframe-2 `extraDraggableSelectors` value: 
`$(top.document).find("iframe:not(#iframe-2)").contents().get()`

#iframe-3 `extraDraggableSelectors` value: 
`$(top.document).find("iframe:not(#iframe-3)").contents().get()`

...and so on...

I've also uploaded a demo for testing here: 
http://manos.malihu.gr/repository/custom-scrollbar/pre-release/examples/iframes-demo/

**Comment by mihai-varga** [comment]
@malihu Thanks! It works perfectly. Looking forward for the next release.

**Comment by malihu** [comment]
The fix is now part of version 3.1.2

**Comment by cngoswami402** [comment]
Hello,

Does this work same on Frameset and Frames ?
I'm having same problem but I have used something as following : 

<FrameSet>
    <Frame>---Header-----</Frame>
    <FrameSet>
        <Frame>---Side Menu that contains scrollbar-----</Frame>
        <Frame>---Content-----</Frame>
    </FrameSet>
</FrameSet>

Please suggest if anything is possible :)

**Comment by Sharje-el** [comment]
Hi, 
I tried the latest version of the plugin, still I am receiving the following error when the application is run under an iframe. 
Please assist.

Uncaught TypeError: true is not a non-null object
