### ISSUE TITLE
max-height problem

### ISSUE THREAD

**Issue by dngrmn1** [malihu/malihu-custom-scrollbar-plugin#9]
I use jquery custom content scroller with .Net in my project.  

Custom content scroller div have height property at default. I want to use css max-height property custom content scroller div. But if i use max-height, custom content scroller doesn't work.

Does any of this help?

**Comment by poshest** [comment]
http://manos.malihu.gr/tuts/custom-scrollbar-plugin/maxheight_example.html link is broken. I can't get the scrollbars working with max-height.  Only height works.  

EDIT:  My bad.  I had the max-height on the parent element.  If you add the max-height to the element that the scrollbar is attached to, it works. Thank you Malihu! :)
