### ISSUE TITLE
Firefox, scroll does not work on an iframe

### ISSUE THREAD

**Issue by xleo77** [malihu/malihu-custom-scrollbar-plugin#91]
If I scroll with the mouse wheel on an iframe within the content, the scroll does not work.

Only in firefox

**Comment by abbas-vohra-wg** [comment]
I am facing the same issue on Mac Safari 8, mousewheel doesn't work

**Comment by malihu** [comment]
Check if the iframe is on the same domain as the host page. If not, the browser prevents js events from running as a security feature.
